name: Suggest an activity
description: Submit an activity for the picker
title: "Suggestion: <activity name>"
labels: ["suggestion"]
body:
  - type: input
    id: activity
    attributes:
      label: Activity
      description: The activity name
      placeholder: e.g., Sunset picnic at Barangaroo
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Seasonal or Permanent?
      options: ["Seasonal","Permanent"]
    validations:
      required: true
  - type: textarea
    id: tags
    attributes:
      label: Tags
      description: Semicolon-separated (e.g. "Outdoors; Scenic")
      placeholder: Outdoors; Scenic
    validations:
      required: true
